#define Uses_EventCodes
#define Uses_MsgBox
#define Uses_TApplication
#define Uses_TBackground
#define Uses_TButton
#define Uses_TChDirDialog
#define Uses_TCheckBoxes
#define Uses_TClipboard
#define Uses_TCluster
#define Uses_TCollection
#define Uses_TColorAttr
#define Uses_TColorDialog
#define Uses_TColorDisplay
#define Uses_TColorGroup
#define Uses_TColorGroupList
#define Uses_TColorItem
#define Uses_TColorItemList
#define Uses_TColorSelector
#define Uses_TCommandSet
#define Uses_TDeskTop
#define Uses_TDialog
#define Uses_TDirCollection
#define Uses_TDirEntry
#define Uses_TDirListBox
#define Uses_TDrawBuffer
#define Uses_TDrawSurface
#define Uses_TEditor
#define Uses_TEditWindow
#define Uses_TEvent
#define Uses_TEventQueue
#define Uses_TFileCollection
#define Uses_TFileDialog
#define Uses_TFileEditor
#define Uses_TFileInfoPane
#define Uses_TFileInputLine
#define Uses_TFileList
#define Uses_TFilterValidator
#define Uses_TFindDialogRec
#define Uses_TFrame
#define Uses_TGroup
#define Uses_THardwareInfo
#define Uses_THistory
#define Uses_THistoryViewer
#define Uses_THistoryWindow
#define Uses_TIndicator
#define Uses_TInputLine
#define Uses_TKeys
#define Uses_TLabel
#define Uses_TListBox
#define Uses_TListViewer
#define Uses_TLookupValidator
#define Uses_TMemo
#define Uses_TMenu
#define Uses_TMenuBar
#define Uses_TMenuBox
#define Uses_TMenuItem
#define Uses_TMenuPopup
#define Uses_TMenuView
#define Uses_TMonoSelector
#define Uses_TMultiCheckBoxes
#define Uses_TNSCollection
#define Uses_TNSSortedCollection
#define Uses_TObject
#define Uses_TOutline
#define Uses_TOutlineViewer
#define Uses_TPalette
#define Uses_TParamText
#define Uses_TPoint
#define Uses_TPReadObjects
#define Uses_TProgram
#define Uses_TPWrittenObjects
#define Uses_TPXPictureValidator
#define Uses_TRadioButtons
#define Uses_TRangeValidator
#define Uses_TRect
#define Uses_TReplaceDialogRec
#define Uses_TResourceCollection
#define Uses_TResourceFile
#define Uses_TResourceItem
// #define Uses_TScreen
#define Uses_TScreenCell
#define Uses_TScrollBar
#define Uses_TScroller
#define Uses_TSearchRec
#define Uses_TSItem
#define Uses_TSortedCollection
#define Uses_TSortedListBox
#define Uses_TStaticText
#define Uses_TStatusDef
#define Uses_TStatusItem
#define Uses_TStatusLine
#define Uses_TStreamable
// #define Uses_TStreamableClass
// #define Uses_TStreamableTypes
#define Uses_TStrIndexRec
#define Uses_TStringCollection
#define Uses_TStringList
#define Uses_TStringLookupValidator
#define Uses_TStrListMaker
#define Uses_TSubMenu
#define Uses_TSurfaceView
#define Uses_TSystemError
#define Uses_TTerminal
#define Uses_TText
#define Uses_TTextDevice
#define Uses_TTimerQueue
#define Uses_TValidator
#define Uses_TView
#define Uses_TVMemMgr
#define Uses_TWindow
#define Uses_ViewCommands
